In [3]:
import pandas as pd

In [4]:
df = pd.read_csv(
    "recipe_dataset.csv"
)

print(df.shape)

df.head()

(15018, 15)

,title,description,ingredients,ingredients_list,instructions,keywords,cuisine,author,image_url,likes,bookmarks,comment_count,popularity_score,cook_steps,url
0,Bắp luộc,#bepvang Món ăn quen thuộc nhưng lại giàu ...,3-5 trái bắp | Ít muối,"['3-5 trái bắp', ' Ít muối']",Bắp lột ít vỏ bắp bên ngoài rửa sạch đ...,"trái bắp,Ít muối",Việt Nam,Phan Bao Van,https://img-global.cpcdn.com/recipes/31335d1dd...,4,1,1,9,3,https://cookpad.com/vn/cong-thuc/15648188
1,Trà sữa Thái,Cách làm món Trà sữa Thái ngon tuyệt của nh...,"20 gr trà Thái | 2,2 lít nước | 1 gói tha...","['20 gr trà Thái', '2,2 lít nước', '1 gói...",Làm thạch: 5gr bột thạch hòa với 500ml n...,"trà Thái,lít nước,gói thạch con cá dẻo...",Việt Nam,Gem,https://img-global.cpcdn.com/recipes/95bf87bec...,0,24,0,48,4,https://cookpad.com/vn/cong-thuc/2318780
2,Sữa điều bí đỏ,Mình nấu theo tổ tiên mâch bảo nên mònh k cân ...,Bí đỏ | Hạt điều | Sữa tươi,"[' Bí đỏ', ' Hạt điều', ' Sữa tươi']",Bí đỏ luộc chín\r\nHạt điều ngâm 2 tiếng rửa s...,"Bí đỏ,Hạt điều,Sữa tươi",Việt Nam,Ching Ching,https://img-global.cpcdn.com/recipes/f5d694786...,6,2,0,10,2,https://cookpad.com/vn/cong-thuc/16223698
3,Cháo hến,#Cookpadapron2025 #monansangchobe Tối ăn cơm c...,200 g hến đã tách vỏ | 2 chén cơm nguội | 20 g...,"['200 g hến đã tách vỏ', '2 chén cơm nguội', '...","Cơm nguội còn dư, thêm 3 chén nước và ít muối,...","hến đã tách vỏ,nguội,hành ngò,hành phi,Gia vị",Việt Nam,Annie Vo,https://img-global.cpcdn.com/recipes/01f6d22c5...,25,3,0,31,3,https://cookpad.com/vn/cong-thuc/17195856
4,Pizza khoai tây hải sản,Một chiếc Pizza được làm từ Đế Khoai Tây vừa m...,1 củ khoai tây | 1 con tôm | 2 khoanh mực ống ...,"['1 củ khoai tây', '1 con tôm', '2 khoanh mực ...","Khoai tây rửa sạch hấp chín, nghiền nhuyễn mịn...","khoai tây,tôm,mực ống,cà chua,Rau củ (ớt chuôn...",Việt Nam,Mẹ Em Nghé,https://img-global.cpcdn.com/recipes/91619421c...,11,11,1,36,7,https://cookpad.com/vn/cong-thuc/16090192

In [8]:
df.isnull().sum()

title                  0
description         2412
ingredients            0
instructions           0
keywords               0
cuisine                0
author                 0
image_url              0
likes                  0
bookmarks              0
comment_count          0
popularity_score       0
cook_steps             0
url                    0
ingredient_count       0
recipe_text            0
dtype: int64

In [9]:
#xóa các dòng trùng lặp dựa trên cột "url"
df.drop_duplicates(
    subset=["url"],
    inplace=True
)

print(df.shape)

(15009, 16)

In [10]:
#xóa dl lỗi
df.dropna(
    subset=[
        "title",
        "ingredients",
        "instructions"
    ],
    inplace=True
)

print(df.shape)

(15009, 16)

In [11]:
#chuẩn hóa text
def clean_text(text):

    if pd.isna(text):
        return ""

    text = str(text)

    text = text.lower()

    text = text.strip()

    text = re.sub(
        r"\s+",
        " ",
        text
    )

    return text

In [ ]:
import re

TEXT_COLUMNS = [

    "title",

    "description",

    "ingredients",

    "instructions",

    "keywords"

]
# chỉ bỏ dấu "
df["title"] = (
    df["title"]
    .astype(str)
    .str.replace(
        '"',
        '',
        regex=False
    )
)
for col in TEXT_COLUMNS:

    if col in df.columns:

        TEXT_COLUMNS = [

            "title",

            "description",

            "ingredients",

            "instructions",

            "keywords"

        ]
        # chỉ bỏ dấu "
        df["title"] = (
            df["title"]
            .astype(str)
            .str.replace(
                '"',
                '',
                regex=False
            )
        )
        for col in TEXT_COLUMNS:

            if col in df.columns:

                df[col] = df[col].apply(
                    clean_text
                )

NameError: name 're' is not defined

In [138]:
# dùng cho ranking sau
df["popularity_score"] = (

    df["likes"] * 2

    +

    df["bookmarks"] * 3

    +

    df["comment_count"]

)

In [139]:
# tính số lượng nguyên liệu
df["ingredient_count"] = (

    df["ingredients"]

    .str.split("|")

    .apply(len)

)

In [140]:
#đếm số bước nấu ăn
df["cook_steps"] = (

    df["instructions"]

    .str.split("|")

    .apply(len)

)

In [13]:
def remove_hashtags(text):

    if pd.isna(text):
        return ""

    text = re.sub(
        r"#\w+",
        "",
        str(text)
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    )

    return text.strip()

df["description"] = (
    df["description"]
    .apply(remove_hashtags)
)

NameError: name 're' is not defined

In [149]:
df["recipe_text"] = (

    df["title"]

    + " "

    + df["description"]

    + " "

    + df["ingredients"]

)

In [143]:
df["recipe_text"] = (
    df["recipe_text"]
    .str.lower()
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

In [150]:
if "ingredients_list" in df.columns:

    df.drop(
        columns=["ingredients_list"],
        inplace=True
    )

In [151]:
df.to_csv(
    "clean_recipe_dataset.csv",
    index=False,
    encoding="utf-8-sig"
)

print(
    "Saved clean_recipe_dataset.csv"
)

Saved clean_recipe_dataset.csv

In [152]:
print(df.shape)

df.head()

(15009, 16)

,title,description,ingredients,instructions,keywords,cuisine,author,image_url,likes,bookmarks,comment_count,popularity_score,cook_steps,url,ingredient_count,recipe_text
0,bắp luộc,món ăn quen thuộc nhưng lại giàu dinh dưỡ...,3-5 trái bắp | ít muối,bắp lột ít vỏ bắp bên ngoài rửa sạch đ...,"trái bắp,ít muối",Việt Nam,Phan Bao Van,https://img-global.cpcdn.com/recipes/31335d1dd...,4,1,1,12,3,https://cookpad.com/vn/cong-thuc/15648188,2,bắp luộc món ăn quen thuộc nhưng lại già...
1,trà sữa thái,cách làm món trà sữa thái ngon tuyệt của nh...,"20 gr trà thái | 2,2 lít nước | 1 gói tha...",làm thạch: 5gr bột thạch hòa với 500ml n...,"trà thái,lít nước,gói thạch con cá dẻo...",Việt Nam,Gem,https://img-global.cpcdn.com/recipes/95bf87bec...,0,24,0,72,4,https://cookpad.com/vn/cong-thuc/2318780,7,trà sữa thái cách làm món trà sữa thái n...
2,sữa điều bí đỏ,mình nấu theo tổ tiên mâch bảo nên mònh k cân ...,bí đỏ | hạt điều | sữa tươi,bí đỏ luộc chín hạt điều ngâm 2 tiếng rửa sạch...,"bí đỏ,hạt điều,sữa tươi",Việt Nam,Ching Ching,https://img-global.cpcdn.com/recipes/f5d694786...,6,2,0,18,2,https://cookpad.com/vn/cong-thuc/16223698,3,sữa điều bí đỏ mình nấu theo tổ tiên mâch bảo ...
3,cháo hến,"tối ăn cơm còn dư, chỉ cần thêm nước và ít muố...",200 g hến đã tách vỏ | 2 chén cơm nguội | 20 g...,"cơm nguội còn dư, thêm 3 chén nước và ít muối,...","hến đã tách vỏ,nguội,hành ngò,hành phi,gia vị",Việt Nam,Annie Vo,https://img-global.cpcdn.com/recipes/01f6d22c5...,25,3,0,59,3,https://cookpad.com/vn/cong-thuc/17195856,5,"cháo hến tối ăn cơm còn dư, chỉ cần thêm nước ..."
4,pizza khoai tây hải sản,một chiếc pizza được làm từ đế khoai tây vừa m...,1 củ khoai tây | 1 con tôm | 2 khoanh mực ống ...,"khoai tây rửa sạch hấp chín, nghiền nhuyễn mịn...","khoai tây,tôm,mực ống,cà chua,rau củ (ớt chuôn...",Việt Nam,Mẹ Em Nghé,https://img-global.cpcdn.com/recipes/91619421c...,11,11,1,56,7,https://cookpad.com/vn/cong-thuc/16090192,8,pizza khoai tây hải sản một chiếc pizza được l...

In [158]:
print(df.iloc[15007]["ingredients"])

1 con gà ta, hoặc có thể sử dụng cánh, đùi, ức mua sẵn, làm sạch, rửa, để ráo | 0.5 ký bí nụ, làm sạch, rửa để ráo | 10-15 nấm đông cô /nấm hương, nấm to thì cắt nhỏ tùy thích | 1 củ carrot, cắt khoanh tròn, tỉa hoa tuỳ thích | 1 bông cải xanh nhỏ, cắt miếng vừa, ngâm muối loãng, rửa sạch, để ráo | 3 nhánh hành lá, cắt khúc | gia vị gồm: muối, hạt nêm, đường, dầu hàu, nước tương, tiêu xay, bột năng | 1 nhánh gừng nhỏ, cắt lát mỏng