In [1]:
!pip install faiss-cpu

Requirement already satisfied: faiss-cpu in C:\Users\pc\AppData\Local\Programs\Python\Python311\Lib\site-packages (1.14.3)
Requirement already satisfied: numpy>=1.25 in C:\Users\pc\AppData\Local\Programs\Python\Python311\Lib\site-packages (from faiss-cpu) (2.4.4)
Requirement already satisfied: packaging in C:\Users\pc\AppData\Local\Programs\Python\Python311\Lib\site-packages (from faiss-cpu) (26.2)

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv(
    "clean_recipe_dataset.csv"
)

embeddings = np.load(
    "recipe_embeddings.npy"
)

print(df.shape)
print(embeddings.shape)

(15009, 16)
(15009, 768)

In [3]:
#chuẩn hóa vector
import faiss

faiss.normalize_L2(
    embeddings
)

In [4]:

#tạo index
dimension = embeddings.shape[1]
index = faiss.IndexFlatIP(
    dimension
)

index.add(
    embeddings
)

print(
    index.ntotal
)
#lưu
faiss.write_index(
    index,
    "recipe.index"
)

print(
    "Saved recipe.index"
)

15009
Saved recipe.index

In [5]:
#hàm tìm kiếm
from sentence_transformers import SentenceTransformer

model = SentenceTransformer(
    "keepitreal/vietnamese-sbert"
)

def search_recipe(
    query,
    top_k=10
):

    query_embedding = model.encode(
        [query],
        convert_to_numpy=True
    )

    faiss.normalize_L2(
        query_embedding
    )

    D, I = index.search(
        query_embedding,
        top_k
    )

    results = df.iloc[
        I[0]
    ][
        [
            "title",
            "ingredients",
            "url"
        ]
    ].copy()

    results["score"] = D[0]

    return results

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

In [6]:
#test
search_recipe(
    "món chay ít calo"
)

,title,ingredients,url,score
6795,mâm cơm chay thường ngày #12,nguyên liệu xem ở từng món,https://cookpad.com/vn/cong-thuc/24506382,0.616549
14243,cơm chay gạo lứt: giảm cân healthy + eatclean,100 gr rau muống | 2 miếng thịt chay | 100 gr ...,https://cookpad.com/vn/cong-thuc/15080124,0.612342
14056,mâm cơm chay thường ngày,nguyên liệu xem tại link đính kèm,https://cookpad.com/vn/cong-thuc/24966484,0.596695
276,món chay: đậu cô ve xào đậu hũ,đậu cô ve | đậu hũ | mộc nhĩ | củ hành,https://cookpad.com/vn/cong-thuc/15847101,0.582927
8647,"ăn kiêng - cơm súp lơ (diet, healthy, keto)","1 súp lơ | 1/4 củ hành tây | hành khô, hạt nêm",https://cookpad.com/vn/cong-thuc/11042932,0.580019
10064,giảm cân - eat clean - d3: nấm bào ngư chiên s...,1 chén gạo lứt nhỏ | 50 gr bào ngư chiên sốt m...,https://cookpad.com/vn/cong-thuc/14631605,0.575950
6399,mâm cơm chay ngày mùng 1,sườn chay rim sả ớt | đùi gà chay khìa nước tư...,https://cookpad.com/vn/cong-thuc/23906344,0.572157
619,cơm chiên chay rau củ,1 củ cà rốt | 1/2 trái bắp vàng | 250 g đậu qu...,https://cookpad.com/vn/cong-thuc/25045201,0.569618
6234,bún gạo lứt xào đỗ thịt giảm cân ít calo,đỗ tươi (tuỳ lượng ăn của các bạn) | 100 g thị...,https://cookpad.com/vn/cong-thuc/14762715,0.568182
10172,mâm cơm chay 30k,nguyên liệu đính kèm theo link từng món,https://cookpad.com/vn/cong-thuc/25337497,0.562147

In [7]:
search_recipe(
    "tôi có tôm và bông cải"
)

,title,ingredients,url,score
7968,canh cải xoăn kale nấu tôm khô,1 bó cải xoăn kale | 1/2 nắm tôm khô | 1 mcf m...,https://cookpad.com/vn/cong-thuc/23981492,0.664614
2536,canh cải ngọt bông cải nấu tôm thịt,1 bó rau cải ngọt | 1 góc bông cải trắng | 100...,https://cookpad.com/vn/cong-thuc/25599858,0.651765
4068,canh cải thìa nấu tôm,200 g tôm tươi | 1 bó cải thìa | 1 muỗng cà ph...,https://cookpad.com/vn/cong-thuc/24967365,0.651156
2820,canh cải ngọt nấu tôm biển,150 g tôm | 300 g rau cải xanh | 1 ít muối | 1...,https://cookpad.com/vn/cong-thuc/15354735,0.648777
9539,canh rau muống tôm nõn,5-6 con tôm nõn rim | 1 nắm rau muống | 1 thìa...,https://cookpad.com/vn/cong-thuc/24167198,0.642979
418,canh cải cúc nấu tôm nõn,1 bát con tôm nõn đã rim | 1 mớ cải cúc | gia ...,https://cookpad.com/vn/cong-thuc/17308649,0.636920
5313,canh cải thìa nấu tôm,150 g tôm | 3 cây cải thìa | 1 ít muối | 1 củ ...,https://cookpad.com/vn/cong-thuc/23964441,0.635551
14568,canh rau má nấu tôm,200 g rau má | 5 con tôm sú | 1 ít muối,https://cookpad.com/vn/cong-thuc/24224362,0.627769
7032,canh cải xanh nấu tôm,1 bó rau cải xanh/cải đắng | 150 gr tôm nõn | ...,https://cookpad.com/vn/cong-thuc/25318232,0.615234
10190,canh cải canh nấu tôm,1 nắm rau cải canh | 20 gram tôm sắt bóc nõn |...,https://cookpad.com/vn/cong-thuc/17180243,0.614881